package machine_test

import (
	"github.com/canonical/lscompute/pkg/machine"
	"github.com/canonical/lscompute/pkg/machine/cpu"
	"github.com/canonical/lscompute/pkg/machine/device/pci"
	"github.com/canonical/lscompute/pkg/machine/disk"
	"github.com/canonical/lscompute/pkg/machine/memory"
)

func init() {
	register("hp-zbook-power-16-inch-g11", machine.Machine{
		CPUs: []cpu.CPU{
			{
				Architecture:   "amd64",
				ManufacturerId: "GenuineIntel",
				Flags:          []string{"fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "dts", "acpi", "mmx", "fxsr", "sse", "sse2", "ss", "ht", "tm", "pbe", "syscall", "nx", "pdpe1gb", "rdtscp", "lm", "constant_tsc", "art", "arch_perfmon", "pebs", "bts", "rep_good", "nopl", "xtopology", "nonstop_tsc", "cpuid", "aperfmperf", "tsc_known_freq", "pni", "pclmulqdq", "dtes64", "monitor", "ds_cpl", "vmx", "smx", "est", "tm2", "ssse3", "sdbg", "fma", "cx16", "xtpr", "pdcm", "pcid", "sse4_1", "sse4_2", "x2apic", "movbe", "popcnt", "tsc_deadline_timer", "aes", "xsave", "avx", "f16c", "rdrand", "lahf_lm", "abm", "3dnowprefetch", "cpuid_fault", "epb", "ssbd", "ibrs", "ibpb", "stibp", "ibrs_enhanced", "tpr_shadow", "flexpriority", "ept", "vpid", "ept_ad", "fsgsbase", "tsc_adjust", "bmi1", "avx2", "smep", "bmi2", "erms", "invpcid", "rdseed", "adx", "smap", "clflushopt", "clwb", "intel_pt", "sha_ni", "xsaveopt", "xsavec", "xgetbv1", "xsaves", "split_lock_detect", "user_shstk", "avx_vnni", "dtherm", "ida", "arat", "pln", "pts", "hwp", "hwp_notify", "hwp_act_window", "hwp_epp", "hwp_pkg_req", "hfi", "vnmi", "umip", "pku", "ospke", "waitpkg", "gfni", "vaes", "vpclmulqdq", "rdpid", "bus_lock_detect", "movdiri", "movdir64b", "fsrm", "md_clear", "serialize", "pconfig", "arch_lbr", "ibt", "flush_l1d", "arch_capabilities"},
			},
			{
				Architecture:   "amd64",
				ManufacturerId: "GenuineIntel",
				Flags:          []string{"fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "dts", "acpi", "mmx", "fxsr", "sse", "sse2", "ss", "ht", "tm", "pbe", "syscall", "nx", "pdpe1gb", "rdtscp", "lm", "constant_tsc", "art", "arch_perfmon", "pebs", "bts", "rep_good", "nopl", "xtopology", "nonstop_tsc", "cpuid", "aperfmperf", "tsc_known_freq", "pni", "pclmulqdq", "dtes64", "monitor", "ds_cpl", "vmx", "smx", "est", "tm2", "ssse3", "sdbg", "fma", "cx16", "xtpr", "pdcm", "pcid", "sse4_1", "sse4_2", "x2apic", "movbe", "popcnt", "tsc_deadline_timer", "aes", "xsave", "avx", "f16c", "rdrand", "lahf_lm", "abm", "3dnowprefetch", "cpuid_fault", "epb", "intel_ppin", "ssbd", "ibrs", "ibpb", "stibp", "ibrs_enhanced", "tpr_shadow", "flexpriority", "ept", "vpid", "ept_ad", "fsgsbase", "tsc_adjust", "bmi1", "avx2", "smep", "bmi2", "erms", "invpcid", "rdseed", "adx", "smap", "clflushopt", "clwb", "intel_pt", "sha_ni", "xsaveopt", "xsavec", "xgetbv1", "xsaves", "split_lock_detect", "user_shstk", "avx_vnni", "dtherm", "ida", "arat", "pln", "pts", "hwp", "hwp_notify", "hwp_act_window", "hwp_epp", "hwp_pkg_req", "hfi", "vnmi", "umip", "pku", "ospke", "waitpkg", "gfni", "vaes", "vpclmulqdq", "rdpid", "bus_lock_detect", "movdiri", "movdir64b", "fsrm", "md_clear", "serialize", "pconfig", "arch_lbr", "ibt", "flush_l1d", "arch_capabilities"},
			},
		},
		Memory: memory.Memory{TotalRam: 33047601152, TotalSwap: 8589930496},
		Disk: []disk.Disk{
			{MountPoint: new("/"), Path: "/fakehost/var/lib/snapd/snaps", Total: 214748364800, Available: 53687091200},
		},
		PCIDevices: []pci.Device{
			{
				Bus:         "pci",
				Slot:        "0000:00:00.0",
				BusNumber:   0x0,
				DeviceClass: 0x600,
				VendorId:    0x8086,
				DeviceId:    0x7D01,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:01.0",
				BusNumber:   0x0,
				DeviceClass: 0x604,
				VendorId:    0x8086,
				DeviceId:    0x7ECC,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:02.0",
				BusNumber:   0x0,
				DeviceClass: 0x300,
				VendorId:    0x8086,
				DeviceId:    0x7DD5,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:04.0",
				BusNumber:   0x0,
				DeviceClass: 0x1180,
				VendorId:    0x8086,
				DeviceId:    0x7D03,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:06.0",
				BusNumber:   0x0,
				DeviceClass: 0x604,
				VendorId:    0x8086,
				DeviceId:    0x7ECB,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:07.0",
				BusNumber:   0x0,
				DeviceClass: 0x604,
				VendorId:    0x8086,
				DeviceId:    0x7EC4,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:07.2",
				BusNumber:   0x0,
				DeviceClass: 0x604,
				VendorId:    0x8086,
				DeviceId:    0x7EC6,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:08.0",
				BusNumber:   0x0,
				DeviceClass: 0x880,
				VendorId:    0x8086,
				DeviceId:    0x7E4C,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:0a.0",
				BusNumber:   0x0,
				DeviceClass: 0x1180,
				VendorId:    0x8086,
				DeviceId:    0x7D0D,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:0b.0",
				BusNumber:   0x0,
				DeviceClass: 0x1200,
				VendorId:    0x8086,
				DeviceId:    0x7D1D,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.0",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0x7EC0,
				SubvendorId:          new(uint16(0x103C)),
				SubdeviceId:          new(uint16(0x8CA0)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.2",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(64)),
				VendorId:             0x8086,
				DeviceId:             0x7EC2,
				SubvendorId:          new(uint16(0x103C)),
				SubdeviceId:          new(uint16(0x8CA0)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.3",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(64)),
				VendorId:             0x8086,
				DeviceId:             0x7EC3,
				SubvendorId:          new(uint16(0x103C)),
				SubdeviceId:          new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:12.0",
				BusNumber:   0x0,
				DeviceClass: 0x700,
				VendorId:    0x8086,
				DeviceId:    0x7E45,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:14.0",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0x7E7D,
				SubvendorId:          new(uint16(0x103C)),
				SubdeviceId:          new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:14.2",
				BusNumber:   0x0,
				DeviceClass: 0x500,
				VendorId:    0x8086,
				DeviceId:    0x7E7F,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:14.3",
				BusNumber:   0x0,
				DeviceClass: 0x280,
				VendorId:    0x8086,
				DeviceId:    0x7E40,
				SubvendorId: new(uint16(0x8086)),
				SubdeviceId: new(uint16(0x90)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:15.0",
				BusNumber:   0x0,
				DeviceClass: 0xC80,
				VendorId:    0x8086,
				DeviceId:    0x7E78,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:16.0",
				BusNumber:   0x0,
				DeviceClass: 0x780,
				VendorId:    0x8086,
				DeviceId:    0x7E70,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:16.3",
				BusNumber:            0x0,
				DeviceClass:          0x700,
				ProgrammingInterface: new(uint8(2)),
				VendorId:             0x8086,
				DeviceId:             0x7E73,
				SubvendorId:          new(uint16(0x103C)),
				SubdeviceId:          new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1c.0",
				BusNumber:   0x0,
				DeviceClass: 0x604,
				VendorId:    0x8086,
				DeviceId:    0x7E3E,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1e.0",
				BusNumber:   0x0,
				DeviceClass: 0x780,
				VendorId:    0x8086,
				DeviceId:    0x7E25,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1e.2",
				BusNumber:   0x0,
				DeviceClass: 0xC80,
				VendorId:    0x8086,
				DeviceId:    0x7E27,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1f.0",
				BusNumber:   0x0,
				DeviceClass: 0x601,
				VendorId:    0x8086,
				DeviceId:    0x7E02,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1f.3",
				BusNumber:   0x0,
				DeviceClass: 0x401,
				VendorId:    0x8086,
				DeviceId:    0x7E28,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1f.4",
				BusNumber:   0x0,
				DeviceClass: 0xC05,
				VendorId:    0x8086,
				DeviceId:    0x7E22,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1f.5",
				BusNumber:   0x0,
				DeviceClass: 0xC80,
				VendorId:    0x8086,
				DeviceId:    0x7E23,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:00:1f.6",
				BusNumber:   0x0,
				DeviceClass: 0x200,
				VendorId:    0x8086,
				DeviceId:    0x550A,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:01:00.0",
				BusNumber:   0x1,
				DeviceClass: 0x302,
				VendorId:    0x10DE,
				DeviceId:    0x28B9,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA3)),
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:02:00.0",
				BusNumber:            0x2,
				DeviceClass:          0x108,
				ProgrammingInterface: new(uint8(2)),
				VendorId:             0x1C5C,
				DeviceId:             0x1959,
				SubvendorId:          new(uint16(0x1C5C)),
				SubdeviceId:          new(uint16(0x1959)),
			},
			{
				Bus:         "pci",
				Slot:        "0000:57:00.0",
				BusNumber:   0x57,
				DeviceClass: 0xFF00,
				VendorId:    0x10EC,
				DeviceId:    0x525A,
				SubvendorId: new(uint16(0x103C)),
				SubdeviceId: new(uint16(0x8CA0)),
			},
		},
	})
}
