package machine_test

import (
	"github.com/canonical/lscompute/pkg/machine"
	"github.com/canonical/lscompute/pkg/machine/cpu"
	"github.com/canonical/lscompute/pkg/machine/device/pci"
	"github.com/canonical/lscompute/pkg/machine/device/usb"
	"github.com/canonical/lscompute/pkg/machine/disk"
	"github.com/canonical/lscompute/pkg/machine/memory"
)

func init() {
	register("xps13-9350", machine.Machine{
		CPUs: []cpu.CPU{
			{
				Architecture:   "amd64",
				ManufacturerId: "GenuineIntel",
				Flags:          []string{"fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "dts", "acpi", "mmx", "fxsr", "sse", "sse2", "ss", "ht", "tm", "pbe", "syscall", "nx", "pdpe1gb", "rdtscp", "lm", "constant_tsc", "art", "arch_perfmon", "pebs", "bts", "rep_good", "nopl", "xtopology", "nonstop_tsc", "cpuid", "aperfmperf", "tsc_known_freq", "pni", "pclmulqdq", "dtes64", "monitor", "ds_cpl", "vmx", "smx", "est", "tm2", "ssse3", "sdbg", "fma", "cx16", "xtpr", "pdcm", "pcid", "sse4_1", "sse4_2", "x2apic", "movbe", "popcnt", "tsc_deadline_timer", "aes", "xsave", "avx", "f16c", "rdrand", "lahf_lm", "abm", "3dnowprefetch", "cpuid_fault", "epb", "ssbd", "ibrs", "ibpb", "stibp", "ibrs_enhanced", "tpr_shadow", "flexpriority", "ept", "vpid", "ept_ad", "fsgsbase", "tsc_adjust", "bmi1", "avx2", "smep", "bmi2", "erms", "invpcid", "rdt_a", "rdseed", "adx", "smap", "clflushopt", "clwb", "intel_pt", "sha_ni", "xsaveopt", "xsavec", "xgetbv1", "xsaves", "split_lock_detect", "user_shstk", "avx_vnni", "lam", "wbnoinvd", "dtherm", "ida", "arat", "pln", "pts", "hwp", "hwp_notify", "hwp_act_window", "hwp_epp", "hwp_pkg_req", "hfi", "vnmi", "umip", "pku", "ospke", "waitpkg", "gfni", "vaes", "vpclmulqdq", "rdpid", "bus_lock_detect", "movdiri", "movdir64b", "fsrm", "md_clear", "serialize", "pconfig", "arch_lbr", "ibt", "flush_l1d", "arch_capabilities"},
			},
		},
		Memory: memory.Memory{TotalRam: 32653012992, TotalSwap: 8589930496},
		Disk: []disk.Disk{
			{MountPoint: new("/"), Path: "/fakehost/var/lib/snapd/snaps", Total: 214748364800, Available: 53687091200},
		},
		PCIDevices: []pci.Device{
			{
				Bus:           "pci",
				Slot:          "0000:00:00.0",
				BusNumber:     0x0,
				DeviceClass:   0x600,
				VendorId:      0x8086,
				DeviceId:      0x6400,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Host Bridge/DRAM Controller", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:02.0",
				BusNumber:            0x0,
				DeviceClass:          0x300,
				VendorId:             0x8086,
				DeviceId:             0x64A0,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0xCC9)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake [Intel Arc Graphics 130V / 140V]", SubvendorName: "Dell"},
				AdditionalProperties: map[string]string{"vram": "30221971456"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:04.0",
				BusNumber:     0x0,
				DeviceClass:   0x1180,
				VendorId:      0x8086,
				DeviceId:      0x641D,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Dynamic Tuning Technology", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:05.0",
				BusNumber:     0x0,
				DeviceClass:   0x480,
				VendorId:      0x8086,
				DeviceId:      0x645D,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake IPU", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:07.0",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0xA84E,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Thunderbolt 4 PCI Express Root Port #0", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:07.2",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0xA860,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Thunderbolt 4 PCI Express Root Port #2", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:0a.0",
				BusNumber:     0x0,
				DeviceClass:   0x1180,
				VendorId:      0x8086,
				DeviceId:      0x647D,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Crashlog and Telemetry", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:0b.0",
				BusNumber:     0x0,
				DeviceClass:   0x1200,
				VendorId:      0x8086,
				DeviceId:      0x643E,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake NPU", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.0",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0xA831,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0xCC9)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Thunderbolt 4 USB Controller", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.2",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(64)),
				VendorId:             0x8086,
				DeviceId:             0xA833,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0xCC9)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Thunderbolt 4 NHI #0", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:0d.3",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(64)),
				VendorId:             0x8086,
				DeviceId:             0xA834,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0xCC9)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Thunderbolt 4 NHI #1", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:12.0",
				BusNumber:     0x0,
				DeviceClass:   0x700,
				VendorId:      0x8086,
				DeviceId:      0xA845,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Integrated Sensor Hub", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:13.0",
				BusNumber:     0x0,
				DeviceClass:   0x780,
				VendorId:      0x8086,
				DeviceId:      0xA862,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M CSME HECI #3", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:14.0",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0xA87D,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0xCC9)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M USB 3.2 Gen 2x1 xHCI Host Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:14.2",
				BusNumber:     0x0,
				DeviceClass:   0x500,
				VendorId:      0x8086,
				DeviceId:      0xA87F,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Shared SRAM", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:14.3",
				BusNumber:     0x0,
				DeviceClass:   0x280,
				VendorId:      0x8086,
				DeviceId:      0xA840,
				SubvendorId:   new(uint16(0x8086)),
				SubdeviceId:   new(uint16(0x40E0)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "BE201 320MHz", SubvendorName: "Intel Corporation"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:14.7",
				BusNumber:     0x0,
				DeviceClass:   0xD11,
				VendorId:      0x8086,
				DeviceId:      0xA876,
				SubvendorId:   new(uint16(0x8086)),
				SubdeviceId:   new(uint16(0xE)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Bluetooth", SubvendorName: "Intel Corporation"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:15.0",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0xA878,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Serial IO I2C Controller #0", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:15.2",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0xA87A,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Serial IO I2C Controller #2", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:16.0",
				BusNumber:     0x0,
				DeviceClass:   0x780,
				VendorId:      0x8086,
				DeviceId:      0xA870,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M CSME HECI #1", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1c.0",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0xA83C,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M PCI Express Root Port #5", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1e.0",
				BusNumber:     0x0,
				DeviceClass:   0x780,
				VendorId:      0x8086,
				DeviceId:      0xA825,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M Serial IO UART Controller #0", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.0",
				BusNumber:     0x0,
				DeviceClass:   0x601,
				VendorId:      0x8086,
				DeviceId:      0xA807,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M LPC Premium Controller/eSPI Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.3",
				BusNumber:     0x0,
				DeviceClass:   0x401,
				VendorId:      0x8086,
				DeviceId:      0xA828,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M HD Audio Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.4",
				BusNumber:     0x0,
				DeviceClass:   0xC05,
				VendorId:      0x8086,
				DeviceId:      0xA822,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M SMbus Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.5",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0xA823,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0xCC9)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Lunar Lake-M SPI Controller", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:71:00.0",
				BusNumber:            0x71,
				DeviceClass:          0x108,
				ProgrammingInterface: new(uint8(2)),
				VendorId:             0x1C5C,
				DeviceId:             0x1F69,
				SubvendorId:          new(uint16(0x1C5C)),
				SubdeviceId:          new(uint16(0x1F69)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "SK hynix", DeviceName: "PVC10 NVMe Solid State Drive (DRAM-less)", SubvendorName: "SK hynix", SubdeviceName: "PVC10 NVMe Solid State Drive (DRAM-less)"},
			},
		},
		USBDevices: []usb.Device{
			{
				Bus:          "usb",
				BusNumber:    3,
				DeviceNumber: 3,
				VendorId:     0x2AC1,
				ProductId:    0x20C9,
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  20,
				VendorId:      0xBDA,
				ProductId:     0x5483,
				FriendlyNames: usb.FriendlyNames{VendorName: "Realtek Semiconductor Corp."},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  24,
				VendorId:      0xBDA,
				ProductId:     0x5483,
				FriendlyNames: usb.FriendlyNames{VendorName: "Realtek Semiconductor Corp."},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  26,
				VendorId:      0xBDA,
				ProductId:     0x8153,
				FriendlyNames: usb.FriendlyNames{VendorName: "Realtek Semiconductor Corp.", ProductName: "RTL8153 Gigabit Ethernet Adapter"},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  25,
				VendorId:      0x45E,
				ProductId:     0x840,
				FriendlyNames: usb.FriendlyNames{VendorName: "Microsoft Corp."},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  21,
				VendorId:      0x46D,
				ProductId:     0xC548,
				FriendlyNames: usb.FriendlyNames{VendorName: "Logitech, Inc.", ProductName: "Logi Bolt Receiver"},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  22,
				VendorId:      0x46D,
				ProductId:     0xC52B,
				FriendlyNames: usb.FriendlyNames{VendorName: "Logitech, Inc.", ProductName: "Unifying Receiver"},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  23,
				VendorId:      0xBDA,
				ProductId:     0x1100,
				FriendlyNames: usb.FriendlyNames{VendorName: "Realtek Semiconductor Corp."},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  8,
				VendorId:      0x27C6,
				ProductId:     0x633C,
				FriendlyNames: usb.FriendlyNames{VendorName: "Shenzhen Goodix Technology Co.,Ltd."},
			},
			{
				Bus:           "usb",
				BusNumber:     1,
				DeviceNumber:  1,
				VendorId:      0x1D6B,
				ProductId:     0x2,
				FriendlyNames: usb.FriendlyNames{VendorName: "Linux Foundation", ProductName: "2.0 root hub"},
			},
			{
				Bus:           "usb",
				BusNumber:     2,
				DeviceNumber:  1,
				VendorId:      0x1D6B,
				ProductId:     0x3,
				FriendlyNames: usb.FriendlyNames{VendorName: "Linux Foundation", ProductName: "3.0 root hub"},
			},
			{
				Bus:           "usb",
				BusNumber:     3,
				DeviceNumber:  1,
				VendorId:      0x1D6B,
				ProductId:     0x2,
				FriendlyNames: usb.FriendlyNames{VendorName: "Linux Foundation", ProductName: "2.0 root hub"},
			},
			{
				Bus:           "usb",
				BusNumber:     4,
				DeviceNumber:  1,
				VendorId:      0x1D6B,
				ProductId:     0x3,
				FriendlyNames: usb.FriendlyNames{VendorName: "Linux Foundation", ProductName: "3.0 root hub"},
			},
		},
	})
}
