package machine_test

import (
	"github.com/canonical/lscompute/pkg/machine"
	"github.com/canonical/lscompute/pkg/machine/cpu"
	"github.com/canonical/lscompute/pkg/machine/device/pci"
	"github.com/canonical/lscompute/pkg/machine/disk"
	"github.com/canonical/lscompute/pkg/machine/memory"
)

func init() {
	register("xps13-7390", machine.Machine{
		CPUs: []cpu.CPU{
			{
				Architecture:   "amd64",
				ManufacturerId: "GenuineIntel",
				Flags:          []string{"fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce", "cx8", "apic", "sep", "mtrr", "pge", "mca", "cmov", "pat", "pse36", "clflush", "dts", "acpi", "mmx", "fxsr", "sse", "sse2", "ss", "ht", "tm", "pbe", "syscall", "nx", "pdpe1gb", "rdtscp", "lm", "constant_tsc", "art", "arch_perfmon", "pebs", "bts", "rep_good", "nopl", "xtopology", "nonstop_tsc", "cpuid", "aperfmperf", "pni", "pclmulqdq", "dtes64", "monitor", "ds_cpl", "vmx", "est", "tm2", "ssse3", "sdbg", "fma", "cx16", "xtpr", "pdcm", "pcid", "sse4_1", "sse4_2", "x2apic", "movbe", "popcnt", "tsc_deadline_timer", "aes", "xsave", "avx", "f16c", "rdrand", "lahf_lm", "abm", "3dnowprefetch", "cpuid_fault", "epb", "ssbd", "ibrs", "ibpb", "stibp", "ibrs_enhanced", "tpr_shadow", "flexpriority", "ept", "vpid", "ept_ad", "fsgsbase", "tsc_adjust", "sgx", "bmi1", "avx2", "smep", "bmi2", "erms", "invpcid", "mpx", "rdseed", "adx", "smap", "clflushopt", "intel_pt", "xsaveopt", "xsavec", "xgetbv1", "xsaves", "dtherm", "ida", "arat", "pln", "pts", "hwp", "hwp_notify", "hwp_act_window", "hwp_epp", "vnmi", "md_clear", "flush_l1d", "arch_capabilities"},
			},
		},
		Memory: memory.Memory{TotalRam: 15908761600, TotalSwap: 4294963200},
		Disk: []disk.Disk{
			{MountPoint: new("/"), Path: "/fakehost/var/lib/snapd/snaps", Total: 214748364800, Available: 53687091200},
		},
		PCIDevices: []pci.Device{
			{
				Bus:           "pci",
				Slot:          "0000:00:00.0",
				BusNumber:     0x0,
				DeviceClass:   0x600,
				VendorId:      0x8086,
				DeviceId:      0x9B61,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake-U v1 4c Host Bridge/DRAM Controller", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:02.0",
				BusNumber:            0x0,
				DeviceClass:          0x300,
				VendorId:             0x8086,
				DeviceId:             0x9B41,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0x962)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "CometLake-U GT2 [UHD Graphics]", SubvendorName: "Dell"},
				AdditionalProperties: map[string]string{"vram": "14477950976"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:04.0",
				BusNumber:     0x0,
				DeviceClass:   0x1180,
				VendorId:      0x8086,
				DeviceId:      0x1903,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:08.0",
				BusNumber:     0x0,
				DeviceClass:   0x880,
				VendorId:      0x8086,
				DeviceId:      0x1911,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:12.0",
				BusNumber:     0x0,
				DeviceClass:   0x1180,
				VendorId:      0x8086,
				DeviceId:      0x2F9,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake Thermal Subsytem", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:14.0",
				BusNumber:            0x0,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0x2ED,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0x962)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCH-LP USB 3.1 xHCI Host Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:14.2",
				BusNumber:     0x0,
				DeviceClass:   0x500,
				VendorId:      0x8086,
				DeviceId:      0x2EF,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCH-LP Shared SRAM", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:15.0",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0x2E8,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Serial IO I2C Host Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:15.1",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0x2E9,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake Serial IO I2C Host Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:16.0",
				BusNumber:     0x0,
				DeviceClass:   0x780,
				VendorId:      0x8086,
				DeviceId:      0x2E0,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake Management Engine Interface", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1c.0",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x2BC,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCI Express Root Port #5", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1c.6",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x2BE,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCI Express Root Port #7", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1d.0",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x2B0,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCI Express Root Port #9", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1d.4",
				BusNumber:     0x0,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x2B4,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCI Express Root Port #13", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.0",
				BusNumber:     0x0,
				DeviceClass:   0x601,
				VendorId:      0x8086,
				DeviceId:      0x284,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCH-LP LPC Premium Controller/eSPI Controller", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:00:1f.3",
				BusNumber:            0x0,
				DeviceClass:          0x403,
				ProgrammingInterface: new(uint8(128)),
				VendorId:             0x8086,
				DeviceId:             0x2C8,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0x962)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCH-LP cAVS", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.4",
				BusNumber:     0x0,
				DeviceClass:   0xC05,
				VendorId:      0x8086,
				DeviceId:      0x2A3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake PCH-LP SMBus Host Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:00:1f.5",
				BusNumber:     0x0,
				DeviceClass:   0xC80,
				VendorId:      0x8086,
				DeviceId:      0x2A4,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Comet Lake SPI (flash) Controller", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:01:00.0",
				BusNumber:     0x1,
				DeviceClass:   0xFF00,
				VendorId:      0x10EC,
				DeviceId:      0x525A,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Realtek Semiconductor Co., Ltd.", DeviceName: "RTS525A PCI Express Card Reader", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:02:00.0",
				BusNumber:     0x2,
				DeviceClass:   0x280,
				VendorId:      0x8086,
				DeviceId:      0x2723,
				SubvendorId:   new(uint16(0x1A56)),
				SubdeviceId:   new(uint16(0x1653)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "Wi-Fi 6 AX200", SubvendorName: "Rivet Networks"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:03:00.0",
				BusNumber:     0x3,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x15D3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:04:00.0",
				BusNumber:     0x4,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x15D3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:04:01.0",
				BusNumber:     0x4,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x15D3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:04:02.0",
				BusNumber:     0x4,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x15D3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:04:04.0",
				BusNumber:     0x4,
				DeviceClass:   0x604,
				VendorId:      0x8086,
				DeviceId:      0x15D3,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 Bridge (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:           "pci",
				Slot:          "0000:05:00.0",
				BusNumber:     0x5,
				DeviceClass:   0x880,
				VendorId:      0x8086,
				DeviceId:      0x15D2,
				SubvendorId:   new(uint16(0x1028)),
				SubdeviceId:   new(uint16(0x962)),
				FriendlyNames: pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 NHI (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:3b:00.0",
				BusNumber:            0x3B,
				DeviceClass:          0xC03,
				ProgrammingInterface: new(uint8(48)),
				VendorId:             0x8086,
				DeviceId:             0x15D4,
				SubvendorId:          new(uint16(0x1028)),
				SubdeviceId:          new(uint16(0x962)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Intel Corporation", DeviceName: "JHL6540 Thunderbolt 3 USB Controller (C step) [Alpine Ridge 4C 2016]", SubvendorName: "Dell"},
			},
			{
				Bus:                  "pci",
				Slot:                 "0000:71:00.0",
				BusNumber:            0x71,
				DeviceClass:          0x108,
				ProgrammingInterface: new(uint8(2)),
				VendorId:             0x144D,
				DeviceId:             0xA808,
				SubvendorId:          new(uint16(0x144D)),
				SubdeviceId:          new(uint16(0xA801)),
				FriendlyNames:        pci.FriendlyNames{VendorName: "Samsung Electronics Co Ltd", DeviceName: "NVMe SSD Controller SM981/PM981/PM983", SubvendorName: "Samsung Electronics Co Ltd", SubdeviceName: "SSD 970 EVO/PRO"},
			},
		},
	})
}
